# logtype can take: debug, info, notice, warning, error, critical
# warning is the default
logtype = "warning"

[default]
# Refresh time in seconde(s). It's an integer
refresh = 5

# Examples
#[[iplist]]
#ip = "192.168.1.1"
#protocol = "tcp"
#portList = ["22:22", "24:24"]
#
#[[iplist]]
#ip = "192.168.1.1"
#protocol = "tcp"
#portList = ["22:24"]
#
#[[iplist]]
#ip = "your.domain.name"
#protocol = "tcp"
#portList = ["22:24"]
#
#[[iplist]]
#ip = "your.domain.name"
#protocol = "udp"
#portList = ["22:24"]