# logtype can take: debug, info, notice, warning, error, critical
# warning is the default
logtype = "info"

[default]
# Refresh accept number of minute(s). It's an integer
refresh = 5

# Example
#[[iplist]]
#ip = "192.168.1.1"
#protocol = "tcp"
#portBegin = 22
#portEnd = 22
#
#[[iplist]]
#ip = "192.168.1.1"
#protocol = "udp"
#portBegin = 22
#portEnd = 22
#
#[[iplist]]
#ip = "my.hostname.com"
#protocol = "tcp"
#portBegin = 22
#portEnd = 22